# original
# - https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-single-broker.yml
version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      HOSTNAME_COMMAND: "hostname -i"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  sbt:
    image: hseeberger/scala-sbt:8u151-2.12.4-1.1.1
    command: 'sbt'
    volumes:
      - $PWD:/mnt
    working_dir: /mnt
    depends_on:
      - zookeeper
      - kafka
